Issue 15: coding guidelines
FireDynamics/ARTSS pull request #113
Opened 2021-01-28 13:18 UTC by LinhWuerzburger

First attempt to close Issue #15, defining coding guidelines. At least the things which are obvious at the moment.

2021-01-28 13:26 UTC, LinhWuerzburger commented
do you think we should add something like: if you want to contribute, pls open a PR?

2021-01-28 13:30 UTC, LinhWuerzburger commented
I changed the name from contributing to coding guidelines because it only has information on the coding guidelines and nothing more. a guide for contributing is in the wiki. the question is: do we want to link to the wiki or not? Or should we make it the other way around and link in the wiki to a markdown file?

2021-01-30 15:01 UTC, ChristianVonMach requested changes
There are some other points in the Googles style guide, that needs to bee addressed. I don't think we should handle all at onces. So this are the thirst few points.

2021-02-03 11:00 UTC, LinhWuerzburger commented on CODING_GUIDELINES.md
> +The coding guidelines of ARTSS are mainly based on the [google coding guidelines](https://google.github.io/styleguide/cppguide.html). Below there are some rules which are not defined in the google st
We don't use C++20 yet see #105 
Regarding the second point, I don't know what you mean with non-standard extension?

2021-02-03 11:30 UTC, LinhWuerzburger commented on CODING_GUIDELINES.md
> +The coding guidelines of ARTSS are mainly based on the [google coding guidelines](https://google.github.io/styleguide/cppguide.html). Below there are some rules which are not defined in the google st
done in 3daa8cf

2021-02-03 11:33 UTC, LinhWuerzburger commented on CODING_GUIDELINES.md
> +The coding guidelines of ARTSS are mainly based on the [google coding guidelines](https://google.github.io/styleguide/cppguide.html). Below there are some rules which are not defined in the google st
If I understand it correctly, you are planning to put every class into a namespace and not only the old static classes? And accordingly to add the rule to put everything in a namespace?

2021-02-03 11:34 UTC, LinhWuerzburger commented on CODING_GUIDELINES.md
> +The coding guidelines of ARTSS are mainly based on the [google coding guidelines](https://google.github.io/styleguide/cppguide.html). Below there are some rules which are not defined in the google st
Can you formulate a passage regarding these rules?

2021-02-03 11:36 UTC, LinhWuerzburger commented on CODING_GUIDELINES.md
> +The coding guidelines of ARTSS are mainly based on the [google coding guidelines](https://google.github.io/styleguide/cppguide.html). Below there are some rules which are not defined in the google st
if adjusted how do you plan to adjust it or do you want to drop the rule?

2021-02-03 11:39 UTC, LinhWuerzburger commented on CODING_GUIDELINES.md
> +The coding guidelines of ARTSS are mainly based on the [google coding guidelines](https://google.github.io/styleguide/cppguide.html). Below there are some rules which are not defined in the google st
I see the benefit in trailing return type syntax only for Lamba expressions. Therefore I propose to adjust the rule to 'for Lambda expressions the trailing return type syntax is used'. Or something similar.

2021-02-03 11:41 UTC, LinhWuerzburger commented on CODING_GUIDELINES.md
> +The coding guidelines of ARTSS are mainly based on the [google coding guidelines](https://google.github.io/styleguide/cppguide.html). Below there are some rules which are not defined in the google st
Is the trailing return type syntax something which can be used for our expressions in GlobalMacrosTypes?

2021-02-03 11:44 UTC, LinhWuerzburger commented
I changed from relying on the google standard to our very own rules which are based on the google standard and in addition, I added that it is NOT necessary to know the google standard. Therefore we have to add every rule from the google standard which we want to use. If the rule is a large passage we can refer to the google standard for more detailed information.

2021-02-03 11:53 UTC, LinhWuerzburger commented
And I don't want to add the rule to not exceed 80 characters per line. This is just way too short. But we should add a section to line breaking. I don't mind to change the limit or to change the whole rule and to say that there won't be a line break at all. But I am not going with 80 characters.

2021-03-09 15:06 UTC, LinhWuerzburger commented
> And I don't want to add the rule to not exceed 80 characters per line. This is just way too short. But we should add a section to line breaking. I don't mind to change the limit or to change the whole rule and to say that there won't be a line break at all. But I am not going with 80 characters.

We could agree on a 100 character hard break while trying to take the 80 character line.

2021-03-12 12:13 UTC, ChristianVonMach commented on CODING_GUIDELINES.md
> +The coding guidelines of ARTSS are mainly based on the [google coding guidelines](https://google.github.io/styleguide/cppguide.html). Below there are some rules which are not defined in the google st
yeas every class should be in a namespace but of course not it's own. I my opinion we should use namespaces to represent the directories in our code like solver or pressure.

2021-03-12 12:15 UTC, ChristianVonMach commented on CODING_GUIDELINES.md
> +The coding guidelines of ARTSS are mainly based on the [google coding guidelines](https://google.github.io/styleguide/cppguide.html). Below there are some rules which are not defined in the google st
"ARTSS currently uses some static and global variables, but do not add new ones except for a exceptional good reason."

2021-03-12 12:19 UTC, ChristianVonMach commented on CODING_GUIDELINES.md
> +The coding guidelines of ARTSS are mainly based on the [google coding guidelines](https://google.github.io/styleguide/cppguide.html). Below there are some rules which are not defined in the google st
trailing return types doesn't work on macros. we still have to relay on our compiler to deduce the correct type.

2021-03-12 12:21 UTC, ChristianVonMach commented on CODING_GUIDELINES.md
> +The coding guidelines of ARTSS are mainly based on the [google coding guidelines](https://google.github.io/styleguide/cppguide.html). Below there are some rules which are not defined in the google st
I think if we go with the rule of 3-5-0 we are going to be okay.

2021-03-15 12:42 UTC, LinhWuerzburger commented on CODING_GUIDELINES.md
> +The coding guidelines of ARTSS are mainly based on the [google coding guidelines](https://google.github.io/styleguide/cppguide.html). Below there are some rules which are not defined in the google st
fine by me. Could you open an issue regarding this discussion? I will think of a text for the guidelines.

2021-03-17 07:50 UTC, LinhWuerzburger commented on CODING_GUIDELINES.md
> +The coding guidelines of ARTSS are mainly based on the [google coding guidelines](https://google.github.io/styleguide/cppguide.html). Below there are some rules which are not defined in the google st
[3-5-0](https://google.github.io/styleguide/cppguide.html#Structs_vs._Tuples) doesn't seem the rule you are speaking of

2021-09-08 14:46 UTC, ChristianVonMach approved these changes

2021-09-08 14:48 UTC, merged