Restructure
FireDynamics/ARTSS pull request #185
Opened 2021-12-09 21:54 UTC by LinhWuerzburger

changed internal structure of multigrid.

GPU lists are now stored in classes which makes it easier to store the necessary parameters like the size of the array and starting index of a specific object/level.

2021-12-14 19:37 UTC, ChristianVonMach requested changes

2021-12-14 22:19 UTC, LinhWuerzburger commented on gtests/Environment.cpp
> +/// \file       Environment.cpp
it is not part of src files, as it is only a class to be executed first for gtest

2021-12-14 22:24 UTC, LinhWuerzburger commented on gtests/boundary/CMakeLists.txt
> +        PRIVATE
05ea776

2021-12-14 22:24 UTC, LinhWuerzburger commented on gtests/CMakeLists.txt
> +        PRIVATE
05ea776

2021-12-14 22:24 UTC, LinhWuerzburger commented on src/analysis/Analysis.cpp
> +    //// weighted 2-norm
cdadf16

2021-12-14 22:24 UTC, LinhWuerzburger commented on src/utility/Utility.cpp
> +    return coordinates;
36da2eb

2021-12-14 22:24 UTC, LinhWuerzburger commented on src/utility/Utility.cpp
> +std::vector<size_t> get_coordinates(size_t index, size_t Nx, size_t Ny) {
36da2eb

2021-12-15 17:32 UTC, ChristianVonMach approved these changes

2021-12-15 17:35 UTC, merged