Restructure 2/2
FireDynamics/ARTSS pull request #189
Opened 2021-12-10 21:22 UTC by LinhWuerzburger

2021-12-14 02:07 UTC, ChristianVonMach commented
Coordinate should use explicit member over a vector

2021-12-15 14:11 UTC, LinhWuerzburger commented
now uniform getInstance calls for domain_data and domain_controller
```
auto domain_data = DomainData::getInstance();
auto domain_controller = DomainController::getInstance();
```

2021-12-19 23:36 UTC, ChristianVonMach requested changes

2021-12-20 10:24 UTC, LinhWuerzburger commented on src/boundaryCondition/SurfaceBoundary.cpp
> +{
pretty sure, we don't have a rule for that yet. At the moment, you can find both in the code. See VCycleMG and ObstacleBoundary for example. 

I would suggest as rule to treat brackets from pragmas the same as namespaces.

2021-12-20 10:39 UTC, merged